package com.rslakra.j2eepatterns.resourcepool;

/**
 * The interface implemented by factories that generate resources to put in
 * the pool
 */
public interface ResourceFactory {
	/**
	 * Create a new resource
	 */
	public Object createResource();
	
	/**
	 * Validate an existing resource generated by this factory. Reset
	 * any parameters to the defaults, or return false if the resource cannot
	 * be reset.
	 */
	public boolean validateResource(Object o);
}
